#数据源配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.200.150
    port: 5672
    username: admin
    password: admin

#   mybatis配置
mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  type-aliases-package: com.bw.cultivate.webtop.dao.entity


jackson:
  date-format: yyyy/MM/dd HH:mm
  time-zone: GMT+8

logging:
  #file:   # 日志文件,绝对路径或相对路径
  #path:   # 保存日志文件目录路径
  #config: # 日志配置文件,Spring Boot默认使用classpath路径下的日志配置文件,如:logback.xml
  level:  # 日志级别
    com.bw.cultivate.webtop: DEBUG # 配置spring web日志级别